spring:
  application:
    name: urbanisme
  data:
    mongodb:
      uri: mongodb+srv://urbanisme:urbanisme@cluster0-hrxdl.mongodb.net/urbanisme?retryWrites=true&w=majority
      database: urbanisme
server:
  port: 8888
app:
  clientId: someClient-id
  clinetSecret: someClient-secret
  accessTokenValidityInSeconds: 20000
  refreshTokenValiditySeconds: 20000
  runningOn: http://localhost:8888;
  unsecuredPath:
    - '/jwt/*'